RESULTS_DIR = "forced_da_analysis"

KICKFILE = "kick"
TFS_SUFFIX = ".tfs"
TIME = "TIME"


INTENSITY_KEY = 'LHC.BCTFR.A6R4.B{beam:d}:BEAM_INTENSITY'
BUNCH_EMITTANCE_KEY = 'LHC.BSRT.5R4.B{beam:d}:BUNCH_EMITTANCE_{plane:s}'
BWS_EMITTANCE_KEY = 'LHC.BWS.5R4.B{beam:d}{plane:s}.APP.{direction:s}:EMITTANCE_NORM'


INTENSITY = "INTENSITY"
EMITTANCE = "EMITTANCE"
NORM_EMITTANCE = "NORM_EMITTANCE"

ROLLING_AVERAGE_WINDOW = 7
CLEAN = "CLEAN"
MEAN = "MEAN"
ERR = "ERR"
