version: 1
disable_existing_loggers: False
formatters:
  plain:
    format: '%(message)s'
  pylhc:
    format: '%(levelname)7s | %(message)s | %(name)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: pylhc
    stream: ext://sys.stdout
  plain:
    class: logging.StreamHandler
    level: INFO
    formatter: plain
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
