# Runs all tests not flagged as "cern_network" with a pytest marker
name: Tests

defaults:
  run:
    shell: bash

on:  # Runs on all push events to any branch that isn't master
  push:
    branches-ignore:
      - 'master'

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        # Make sure to escape 3.10 with quotes so it doesn't get interpreted as float 3.1 by GA's parser
        python-version: [3.7, 3.8, 3.9, "3.10"]
        exclude:
          - os: windows-latest
            python-version: 3.10  # jpype1 doesn't build there
          # - os: macos-latest
          #   python-version: 3.10  # jpype1 doesn't build there

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Get full Python version
        id: full-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: Install package
        run: python -m pip install '.[test]'

      - name: Run basic tests
        run: python -m pytest -m "not cern_network" --mpl --cov-report xml --cov=pylhc
